version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-spring
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: apidb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistencia de datos

  tekton-app:
    image: openjdk:17-jdk-slim  # Ajusta según tu JDK
    container_name: tekton-app
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run  # Usa ./gradlew bootRun si es Gradle

volumes:
  postgres_data:


version: '3.8'

services:
  db:
    image: postgres:15
    container_name: api_postgres
    environment:
      POSTGRES_DB: apidb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring_api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/apidb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

volumes:
  pgdata:
