version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-spring
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: apidb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistencia de datos

  tekton-app:
    image: eclipse-temurin:21-jdk
    container_name: tekton-app
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run

volumes:
  postgres_data:  # Declaración del volumen



